sources:
  - Kalnia-Glaze.glyphs
buildStatic: true
buildVariable: true
buildTTF: true
buildOTF: false
buildWebfont: true
axisOrder:
  - wght
  - wdth
outputDir: "../fonts"
familyName: 'Kalnia Glaze'
recipeProvider: googlefonts
recipe:
  ../fonts/variable/Kalnia-Glaze[wdth,wght].ttf:
    - source: Kalnia-Glaze.glyphs
    - operation: buildVariable
    - operation: fix
    - operation: paintcompiler
      args: -p paints.py
