sources:
  - Kalnia-Glaze.glyphs
buildVariable: true
buildStatic: false
buildWebfont: false
axisOrder:
  - wght
  - wdth
familyName: 'Kalnia Glaze'
recipeProvider: googlefonts
recipe:
  ../fonts/variable/Kalnia-Glaze-Test[wdth,wght].ttf:
    - source: Kalnia-Glaze.glyphs
    - operation: buildVariable
    - operation: fix
    - operation: paintcompiler
      args: -p ../paintcompiler-test/paints.py
