sources:
  - KalniaGlaze.glyphs
buildStatic: true
buildVariable: true
buildTTF: true
buildOTF: false
buildWebfont: true
axisOrder:
  - wght
  - wdth
outputDir: "../fonts"
familyName: 'Kalnia Glaze'
recipeProvider: googlefonts
recipe:
  ../fonts/variable/KalniaGlaze[wdth,wght].ttf:
    - source: KalniaGlaze.glyphs
    - operation: buildVariable
    - operation: fix
    - operation: buildStat
    - operation: paintcompiler
      args: -p paints.py
